// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// prettier-ignore
const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:8f54a1ad-b23e-4bf0-91be-6f17490dcbb4",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_Vh4XZCoiX",
    "aws_user_pools_web_client_id": "6cura4v3dgck6uf9n6efjjt9pg",
    "oauth": {
        "domain": "bdecust-dev-auth.auth.ap-northeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost/",
        "redirectSignOut": "http://localhost/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "bdecust-dev-api-v1",
            "endpoint": "https://m2mdx1rfui.execute-api.ap-northeast-1.amazonaws.com/dev/v1/api",
            "region": "ap-northeast-1"
        },
        {
            "name": "bdecust-dev-cdn-v1",
            "endpoint": "https://m2mdx1rfui.execute-api.ap-northeast-1.amazonaws.com/dev/v1/cdn",
            "region": "ap-northeast-1"
        },
        {
            "name": "bdecust-dev-noneauth-v1",
            "endpoint": "https://m2mdx1rfui.execute-api.ap-northeast-1.amazonaws.com/dev/v1/noneauth",
            "region": "ap-northeast-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://pxdmydiimzexnejbzog4unl6fq.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "bde-dev-file",
    "aws_user_files_s3_bucket_region": "ap-northeast-1",
    "aws_content_delivery_bucket": "bde-dev-cms",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "bde-dev-src"
};
export default awsmobile;
